[package]
name = "satsolver"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
env_logger = "0.11.8"
itertools = "0.14.0"
log = "0.4.27"
rand = "0.9.2"
